import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { library } from "./[book]/[page]/library";

const listOfBooks = Object.entries(library);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} antialiased h-screen flex flex-col`}
      >
        <header className="p-4 shadow-md bg-gray-50 font-serif flex gap-5 items-baseline">
          <h1 className="font-bold">
            <Link href="/" className="text-gray-800 hover:underline">
              🦊 Children Stories
            </Link>
          </h1>
          <nav className="hidden md:flex text-gray-600 gap-3">
            {listOfBooks.map(([id, book]) => (
              <Link key={id} href={`/${id}/1`} className="hover:underline">
                {book.title}
              </Link>
            ))}
          </nav>
        </header>

        {children}

        
        <footer className="text-gray-500 p-4 shadow-md bg-gray-50 font-serif text-sm text-center">
          Made by <Link href="https://www.alexanderhorner.com" className="hover:underline">Alexander Horner</Link> © 2025
        </footer>
      </body>
    </html>
  );
}